### PR TITLE
General code improvements

### PR DESCRIPTION
**Pull request by GaryJones**
Formats code to match with jshints defaults. Some people are fussy and would do this anyway (and those that aren't bothered, aren't bothered), so for the sake of a few extra braces and whitespace, it would be better to have it completed in core. The JS can always be minified by those that want to save a few extra bytes.

Adds some basic documentation - mostly comments for each function or block of code.

Removes replaceState bit of code, since it seemed to be replacing the last history item with exactly the same details. Not sure if I misunderstood why this was present in the first place.

Removes duplicate `var newBlocks = ...` line.

Incorporates the changes made in #9.

Adds 'use strict'; statement.

Obviously, please test on your own setup before merging.

NOT DONE:
Bumped version
Added me as a contributor ;-)

### CODE REVIEW

**Comment by beezee** [comment]
All very nice thanks Gary - if you put the initial replaceState back I'll pull this. It only runs on hard refreshes (when the plugin initializer is triggered) and is necessary to make the initial page load navigable via djax. Without it you should notice if you use the back button the dom will not update going from 2nd page to 1st.

**Comment by GaryJones** [comment]
replaceState added back in. I've also added the speed-click proofing in, with the only slight difference being the conditional return on line 60 being included with the conditional return when handling exceptions. It may be more prudent to set this as individual conditional return at the start of attachClick (following good practice of always returning early where possible) but I didn't want to have my logic too different from yours for this commit.

**Comment by beezee** [comment]
Awesome thanks Gary.

The reason for the seperate conditionals in attachClick is behavioral - one occurs before the preventDefault() and the other afterwards. More specifically, if you click a link set as an exception, it needs to return before the preventDefault so regular behavior can take over. 

For speed clicking, I had intended that it simply would not respond to additional clicks, letting the user calm down and click again with more intent without having to do a full reload of the page. The way you have it right now, speed clicks would cause default link behavior to take over and a full page refresh would occur. I'm open to feedback on this detail, was this your intention?

**Comment by GaryJones** [comment]
Ah, right yes. If we're already doing djaxing, then not only do we NOT want another round of djaxing to occur (return), but also the standard click pass through should fail too (preventDefault). I'll amend my pull request.

**Comment by GaryJones** [comment]
Is the assignment to lastBlock still needed? The variable isn't used anywhere.

**Comment by beezee** [comment]
That one looks like cruft, you can remove it.

**Comment by beezee** [comment]
Thanks for all of this Gary. I'm pulling this and will change 'click.djax' back to 'click' - because it's chained off the filter it will still target the correct links on page, and the 'click.djax' modification seemed to create inconsistent behavior on the click bindings after rapid navigation with the back/forward browser buttons

**Comment by beezee** [comment]
The pull request could not be automatically merged, so I've overwritten and committed, and will close this pull. I've added you as a contributor in the comments, but I think the only way to get you on the Github contributors list is to merge through them. Go ahead and add an extra line of comments at the top, then open a new pull (note the changes I've made as well) and I'll do an automatic pull to get your name on there.

**Pull request closed without merging**
